# Generated by Django 4.0.1 on 2022-01-21 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('LIVE', 'Live'), ('BLOCKED', 'Blocked'), ('RESTRICTED', 'Restricted')], max_length=255)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reports', to='core.url')),
            ],
        ),
    ]
