# Generated by Django 3.2.11 on 2022-01-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220121_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('LIVE', 'Live'), ('BLOCKED', 'Blocked'), ('RESTRICTED', 'Restricted'), ('HACKED', 'Hacked')], max_length=255),
        ),
    ]
